python run_image_classification.py  \
   --dataset_name cifar10  \
   --output_dir ./cifar10_hbfp2,64/  \
   --overwrite_output_dir \
   --remove_unused_columns False  \
   --do_train  \
   --do_eval  \
   --push_to_hub  \
   --push_to_hub_model_id vit-base-cifar10  \
   --learning_rate 5e-5  \
   --num_train_epochs 10  \
   --per_device_train_batch_size 8  \
   --per_device_eval_batch_size 8  \
   --logging_strategy steps  \
   --logging_steps 10  \
   --evaluation_strategy epoch  \
   --save_strategy epoch  \
   --load_best_model_at_end True  \
   --save_total_limit 5  \
   --seed 42  \
   --gradient_accumulation_steps 4  \
   --adam_beta1 0.9  \
   --adam_beta2 0.999  \
   --adam_epsilon 1e-08  \
   --lr_scheduler_type linear \
   --optim BFPAdam