exceptions:
      attn:
         layer_idx: [11]
         modifications:
            num_format: bfp
            w_sparsity: True
      feed_forward:
         layer_idx: [11]
         modifications:
            num_format: bfp
            w_sparsity: True