hbfp:
   num_format: 'bfp'
   sparsity_num_format: 'fp32' 
   rounding_mode: 'stoc' 
   epsilon: 0.00000001 
   mant_bits: 5 
   weight_mant_bits: 15 
   bfp_tile_size: 8
   bfp_block_size: 64 
   in_sparsity: False
   w_sparsity: True
   grad_sparsity: False
   rearrange: False
   sparsity_frac: 0.5
   N: [2]
   M: [4]
   unconstrained: False
   bit_range: []
   device: 'cuda'
