hbfp:
   num_format: 'bfp'
   sparsity_num_format: 'bfp' 
   rounding_mode: 'stoc' 
   epsilon: 0.00000001 
   mant_bits: 3 
   weight_mant_bits: 15 
   bfp_tile_size: 8
   bfp_block_size: 64 
   in_sparsity: False
   w_sparsity: True
   grad_sparsity: False
   rearrange: False
   sparsity_frac: 0.6
   N: [7]
   M: [8]
   unconstrained: False
   bit_range: []
   exceptions:
   - bfp_matmul:
       - mant_bits: 5
   device: 'cuda:0'
