hbfp:
   attn:
      sparsity_num_format: bfp
      a_num_format: fp
      a_mant_bits: 16
      w_num_format: int
      w_mant_bits: 4
      block_size: 1024 
      w_sparsity: True
      N: 2
      M: 4
      first: s
      sparsity_mode: structured
      device: cuda
      sparsify: True
      sparsity_frac: 0.5
      layer_ids: []

   fc1:
      sparsity_num_format: bfp
      a_num_format: fp
      a_mant_bits: 16
      w_num_format: int
      w_mant_bits: 4
      block_size: 1024 
      w_sparsity: True
      N: 2
      M: 4
      first: s
      sparsity_mode: structured
      device: cuda
      sparsify: True
      sparsity_frac: 0.5
      layer_ids: [6, 7, 8, 9, 10]

   fc2:
      sparsity_num_format: bfp
      a_num_format: fp
      a_mant_bits: 16
      w_num_format: int
      w_mant_bits: 4
      block_size: 1024 
      w_sparsity: True
      N: 2
      M: 4
      first: s
      sparsity_mode: structured
      device: cuda
      sparsify: True
      sparsity_frac: 0.5
      layer_ids: [6, 7, 8, 9, 10]
