hbfp:
   num_format: 'bfp'
   sparsity_num_format: 'mx' 
   rounding_mode: 'stoc' 
   epsilon: 0.00000001 
   mant_bits: 7 
   weight_mant_bits: 15 
   block_size: 32 
   in_sparsity: False
   w_sparsity: True 
   grad_sparsity: False
   sparsity_frac: 0.5
   N: 2
   M: 4
   unconstrained: 
   first: q
   sparsity_mode: unstructured
   bit_range: 
   bfloat: 16
   scale_bits: 8
   mx_w_elem_format: fp8_e4m3
   mx_a_elem_format: fp8_e4m3
   device: 'cuda'
