hbfp:
   num_format: 'bfp'
   sparsity_num_format: 'bfp' 
   rounding_mode: 'stoc' 
   epsilon: 0.00000001 
   mant_bits: 7 
   weight_mant_bits: 15 
   bfp_tile_size: 8 
   bfp_block_size: 2 
   in_sparsity: False
   w_sparsity: True 
   grad_sparsity: False
   sparsity_frac: 0.4 
   device: 'cuda'
