hbfp:
   num_format: 'bfp'
   sparsity_num_format: 'bfp' 
   rounding_mode: 'stoc' 
   epsilon: 0.00000001 
   mant_bits: 7 
   weight_mant_bits: 15 
   bfp_tile_size: 64
   bfp_block_size: 64 
   in_sparsity: False
   w_sparsity: False
   grad_sparsity: False
   rearrange: False
   sparsity_frac: 0.6
   N: [8]
   M: [16]
   unconstrained: True
   bit_range: [1,7]
   device: 'cuda:0'
